name: Continuous integration

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore test/Cahoots.UnitTests/Cahoots.UnitTests.csproj

    - name: Build
      run: dotnet build test/Cahoots.UnitTests/Cahoots.UnitTests.csproj --configuration Release --no-restore
        
    - name: Test
      run: dotnet test test/Cahoots.UnitTests/Cahoots.UnitTests.csproj  --no-restore --verbosity normal